### ISSUE TITLE
Validate & coerce form data type

### ISSUE THREAD

**Issue by Leonidaz0r** [amiv-eth/amivapi#105]
We don't check for wrong data types.

For example sending a POST with user_id: "1" and group_id: "1" to  /groupusermembers with a self-enrollment enabled group will not result in an error because of wrong data types (string instead of int), but fails with 403 as comparisons of the user_id parameter to the logged in user ID fails. That is very hard to debug, therefore we should check datatypes first.

Also there might be hidden security vulnerabilities as a consequence of not checking data types.

**Comment by fubu** [comment]
Just FYI, as I ran into a similar thing in another project: SQLAlchemy does not really care. `session.query(User).get(1)` and `session.query(User).get("1")` both work and return the user with id 1.

**Comment by NotSpecial** [comment]
Maybe this is weird behaviour for id, but generally every type is being validated (e.g. type string)

Will check the problem.

**Comment by NotSpecial** [comment]
I found the problem: The type "objectid", which is assigned to the id fields is validated like this:

```python
def _validate_type_objectid(self, field, value):
        """
        This field doesn't have a meaning in SQL
        """
        pass
```

As you see: Not at all validated. Only because the objectids also have to be unique as well the validation fails if a wrong input is given since it cannot be found in the database.

For code integrity we should probably cast all objectid to integers with the new "coerce" function of cerberus and eve. This will ensure we always deal with the appropriate data type.

We can additionally use this feature for all non-text values we accept to make the api more easliy accessible (since all data can be submitted in forms then instead of needing json)

**Comment by NotSpecial** [comment]
Since we are leaving SQL and therefore eve-sqlalchemy the missing validation of the objectid will not be relevant anymore.

I'm keeping this issue open for the moment until I got time to look at the "coercing" feature.

**Comment by NotSpecial** [comment]
Coercing seems to work and not to be too hard to implement, but unfortunately the functionality in eve (see [here](https://github.com/nicolaiarocci/eve/blob/8d20a389cfa45572afa9ed4669a591b4d22d5f2f/eve/methods/post.py#L191-L194)) is not available in the version we can use (<0.6 because of eve-sqlalchemy)

I will put my playing around in a branch to store it for the futute.

**Comment by NotSpecial** [comment]
Here you go: d18c61ab6c2c36ff079562fe4ce5cbf0a677fdfd

**Comment by NotSpecial** [comment]
The newest eve version can do this already for integers, I have created a pull request to add this for booleans as well. So we dont need this anymore.
