### ISSUE TITLE
Remove PUT from all resources

### ISSUE THREAD

**Issue by NotSpecial** [amiv-eth/amivapi#109]
Do we need PUT?

According to definition (http://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html) PUT is used to replace an item or put an item in a certain location.

I think we do not need this behaviour. All changes to existing objects are covered by PATCH, and more efficiently so since PATCH works with subsets of fields while PUT always requires all fields regardless of whats being changed.

Furthermore I cant think of a usecase for placing an item under a certain id.

At the end of the day PUT adds several hooks and tests the API code which is basically for nothing.

I would go for "less is more" and remove PUT from allowed methods for all resources.

Opinions? Usescases where our API needs PUT?

**Comment by hermannsblum** [comment]
If i remember correctly PUT is anyway implemented by eve simply by DELETE and POST.

**Comment by NotSpecial** [comment]
Not sure if I get your point. This is what PUT is supposed to do, yes.

Would you agree with me that it is not necessary or am I missing what you are trying to say?

**Comment by hermannsblum** [comment]
According to the definition, PUT should perform a replacement, i.e. the contents of an item are replaced, but internal states such as an index are preserved.
Actually I was wrong above and eve handles PUT as an replacement, so PUT provides functionality we would not have otherwise.

I can not think of a single use case for PUT right now and therefore would agree that it is unnecessary.
However, I also can not see a benefit in removing access methods.

**Comment by NotSpecial** [comment]
Regarding PUT: Well, thats what happens ^^

Regarding benefit: As I said in my first post, without put we could remove some code (hooks and tests) which just exists because of a method that will never be used

**Comment by NotSpecial** [comment]
Correction about PUT, I read your comment wrong:

Yes, preserving the index is as far as i see the benefit of put, but like you I don't see a usecase

**Comment by hermannsblum** [comment]
> Regarding benefit: As I said in my first post, without put we could remove some code (hooks and tests) which just exists because of a method that will never be used
I think the API should be as open to standards as possible and what access methods an user uses should be up to her/him. As we already implemented PUT and it is, to my knowledge, not causing problems, why reduce the access?

**Comment by NotSpecial** [comment]
Because I believe we should try to keep our code as small as possible to facilitate unterstanding for new members (less code to understand).

While I dont think removing PUT will have a very big impact on this, Im always pro removing unnecessary code.

**Comment by Tar-Tarus** [comment]
Still a bit unclear but the decision of the first day of coding seems to be that they shall be deleted.

**Comment by hermannsblum** [comment]
Yes, we decided to do this and I think @NotSpecial already implemented this? Searched through the commits but could not find it.

**Comment by Tar-Tarus** [comment]
A little search through the files shows that __*"PUT"*__ only appears in two files:
- __amivapi/manage.py__
- __amivapi/mongo_manage.py__
- __amivapi/amivapi/settings.py__
- __amivapi/amivapi/groups/mailing_lists.py__
- __amivapi/amivapi/groups/validation.py__

Could someone review the use of it and correct it if necessary in order to close this issue?

**Comment by Leonidaz0r** [comment]
All of those files are not part of the current code in the mongo branch, so
the problem should disappear after an eventual merge. We should revisit the
issue at that point.

Am 28.10.2016 10:54 nachm. schrieb "Tar-Tarus" <notifications@github.com>:
