### ISSUE TITLE
LDAP Login

### ISSUE THREAD

**Issue by Leonidaz0r** [amiv-eth/amivapi#11]
Implement to reroute the login to LDAP and when credentials match there login the user without local password check.

**Comment by NotSpecial** [comment]
fubus LDAP Tool supports this already, I will try to integrate it into the API

The flow should be like this:

 ...

Post to /sessions with username and password

First: Try login with LDAP (since this is the majority of users)

-> If successful, update user data from ldap

-> If unsuccessful, try to login with database


...

This way, everybody can set a specific AMIV password in case he doesn't want to trust us with his nethz credentials

**Comment by NotSpecial** [comment]
Update: This works now :) 

currently still in Branch LDAP, so I will keep the issue open for the moment

**Comment by NotSpecial** [comment]
Done in 65bb0007c2f2f0163aa4f5511944f7c44b2d1ac1
