### ISSUE TITLE
Workflow and Code review

### ISSUE THREAD

**Issue by NotSpecial** [amiv-eth/amivapi#114]
I am afraid one think we are very much lacking is code review. In most cases every piece of code was written by a single person and never checked by anyone else.

To improve coding style we really have to start reviewing others code!

Do you have any idea how to handle this properly?

There is a very nice [branching model](http://nvie.com/posts/a-successful-git-branching-model/) on how to use git branches effectively.

But my biggest concern is that we are but a few coders. Is this system maybe an overkill?

Do you maybe have other ideas? I think we definetly need to get some more planning in our workflow.

**Comment by fubu** [comment]
You propose code review (:+1:!), but complain about too little planning in the end of your post. That's two very different things at opposite ends of the development timeline :)

What we need is a governance model. Altough we're not a big open-source project (yet? ;)) we need some processes set up:

1. Who decides on, and enforces the roadmap?
2. How to propose, discuss and implement new features?
3. How do they get merged & released?
4. How to maintain a certain code quality?

I don't have a definitive answer, mostly because I'm not an active code contributor for the time being (and I think those who do should have a major voice in that discussion). But I think the answer to the first question should somehow include the IT executive; the second should be mainly in the open (with "private" discussions summarized in the issues here); the third could include some variation of fork/branch/pull-request/code-review/squash-and-rebase/merge; and the fourth should happen before a new feature is merged.

Some things can be supported through automation: At work we have various code-quality related tests: of course for `pep8`-compliance, and also for formatting, naming schemas, usage of bad/ambiguous words, working imports etc. (Travis [supports running tests on pull requests](https://docs.travis-ci.com/user/pull-requests), which is probably a god start.)

I'm also a big fan of "code ownership": Some developers are experts in certain areas of the code, and they should be included in discussions and reviews related to these code areas where possible.

Another important aspect is of course that any such process needs to scale: The AMIV IT team constantly changes/evolves/fluctuates, so these processes should also work with new people, less skilled people (to a certain extent), and especially with completely different people than us right now (e.g., in 2-3 years).

**Comment by NotSpecial** [comment]
I think we now have a better grasp on how to do this. The master branch is protected and requires a review, everything else can be done over feature branches.
