### ISSUE TITLE
Documentation of Use Cases and Reasons Behind API and Data fields

### ISSUE THREAD

**Issue by hermannsblum** [amiv-eth/amivapi#119]
During the discussion about #117 it occurred to us that a lot of previous discussions got forgotten about why we introduced certain api fields.  
It is therefore necessary that we document the reason and function behind every api field in 2 ways:
1. the public documentation of api fields  -> /docs
2. the user and/or admin documentation for more technical background and all data fields

However, we need to agree on a format for this

**Comment by NotSpecial** [comment]
First of all I would separate those issues.

# Technical stuff

Issue 2 is about implementation. I do not think it is helpful to create an additional document for this. This information is only relevant if looking at the code, so I believe it should best stay right in the code. This means our docstrings and comments should be detailed enough to understand the implementation (since no-one will probably ever realize there is a second document with explanations

# Use cases

I think this is more "meta" and therefore deserves its own document which can (and should) be used to verify if the API behaves as needed. I think it would be most helpful and intuitive to write those usecases from a users perspective.

So first of all I would define the different kinds of users we can have, e.g.

> # Different kinds of users:
> * Public:
>  This user is not logged in. He just visited the website etc.
> * ETH:
>  This user is logged, but is no member
> * Member:
>  This user is logged in and a member
> * Group Member:
>  This user is a logged in and member of a certain group. This might or might not grant additional privilege.

Note: This is not final, we should still settle if ETH-but-no-amiv people should be able to log in and if groups should grant access to certain items. But while not just decide on that as well because obviously we need that.

Next I would define the possible interactions with the resources along with their general purpose.

E.g.

> # Groups
>
> A group is a team within the organization. E.g. the "Vorstand" (board) or "Kulturteam" (event team) would be groups. Groups need one or more email adresses to reach them and should allow external addresses to be added
> 
> Public:
> A public user should not be able to be part of a group, but his mail address could end up in one. He needs to be able to remove it.
>
> ETH:
> ETH members should be able to join certain "public" groups. They should not be able to see private or member-only groups or their members.
>
> Members:
> Members should be able to join some groups publicly available to members as well, like a "Helfer" (helpers) group. They should not be able to see private groups or their members.
>
> Group member:
> A group member should be able to leave this group and see everyone in his group. But obviously only for groups he is a member of.

Of course this is not all we need for groups, but would be my general approach. Comments?

**Comment by NotSpecial** [comment]
I have created a first draft in 906db18.

Feel free to help writing! You can even use the github online editor or something like prose.io to make your life super easy ;)

**Comment by NotSpecial** [comment]
My main question would be how "meta" we want to write this. How much do we want to refer to resource/field names?
