### ISSUE TITLE
Error handling when using wrong/outdated Etag

### ISSUE THREAD

**Issue by CupCakeArmy** [amiv-eth/amivapi#125]
If using a wrong ETag, the api returns a "No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://vms04.ethz.ch' is therefore not allowed access. The response had HTTP status code 412." and not a 'Real' error

**Comment by hermannsblum** [comment]
Concerning the 412 error [the RFC about the If-Match Headers](https://tools.ietf.org/html/rfc7232#page-19) introduces this exact error code, so that should be correct 😉. 412 indicates that the error lays in the header and not in the content of the request.

What did you use to make the request? 

with the following code: 
 
    import requests
    from base64 import b64encode

    api = "https://amiv-apidev.vsos.ethz.ch"
    login = requests.post(api + "/sessions",
                          data={"user": "root", "password": "amivroot"},
                          verify=False)
    token = login.json()['token']
    auth_header = b64encode(token + ':')

    response = requests.get(api + '/events/1', verify=False)
    # etag = response.json()['_etag']
    etag = 'x'
    response = requests.patch(api + '/events/1', verify=False,
                              auth=requests.auth.HTTPBasicAuth(token, ""),
                              headers={"If-Match": etag,
                                       "Accept": "application/json"},
                              data={'spots': 11})
    print(response.status_code)
    print(response.text)

I get 

    412
    <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
    <title>412 Precondition Failed</title>
    <h1>Precondition Failed</h1>
    <p>Client and server etags don't match</p>

which looks like a proper description of what went wrong.

**Comment by Tar-Tarus** [comment]
Not an issue afterall. ☁ ▅▒░☼‿☼░▒▅ ☁

**Comment by Leonidaz0r** [comment]
The original error was caused by the CORS settings, not by the missing etag. However that has been fixed as well. Just for the record.
