### ISSUE TITLE
Authentication example wrong in docs

### ISSUE THREAD

**Issue by gingeneer** [amiv-eth/amivapi#137]
The docs/User_guide.md lists 
`POST /sessions?user=mynethzormail&password=mypassword` as an example for authentication, which does not work as far as I know.

**Comment by hermannsblum** [comment]
this is I guess just one example of the many outdated descriptions in our docs 😉

**Comment by hermannsblum** [comment]
It should be resolved with more and more sophisticated eve-swagger? see #140

**Comment by hermannsblum** [comment]
There is actually a code example now given for exactly this problem in #145.

The issue remains how we want to structure all our documentation. Which one goes into `/docs`?

**Comment by NotSpecial** [comment]
I will take a look at this.

The way I see it all reasoning for code should be right in the code. The only thing one needs would be a pointer in the README on where to start reading. 
Especially the outdated developer docs would be obsolete then.

The user guide can maybe changed into a tutorial, but I guess useful examples on /docs would be even better than that since a REST API is not that complicated ^^
