### ISSUE TITLE
Endpoint for sending emails

### ISSUE THREAD

**Issue by temparus** [amiv-eth/amivapi#177]
There should be an endpoint for sending emails to a mailinglist.
As the announce tool is client-side only, there is no way for sending an email directly.

**Comment by NotSpecial** [comment]
Not completely sure about this.

But before I can form a proper opinion:

- How exactly is the announce mail sent, which eth does this?

- Does this tool have its own api?

Afaik sending the announce mail not just like sending a regular mail, right?

**Comment by temparus** [comment]
The announce is sent as a normal email to an email address dictated by the sympa mailing list server.
The new announce tool gets the event data from the API and the builds the email content.
Its logic is completely written in JavaScript.

Handling the bounces is done by the mailing list server.

**Comment by NotSpecial** [comment]
Still not sure if we should put it in the api, although I don't see any obvious points against it. Other opinions?

Aside from that, with Javascript you can just delegate sending to the users mail program, filling in address, subject and body so the user just has to hit 'send'
https://stackoverflow.com/questions/7381150/how-to-send-an-email-from-javascript

**Comment by temparus** [comment]
Delegate sending the email to the users mail program requires that the user has configured such a program on his computer. I am against this option as I only use webmail as some others do as well.

Another option would be to host an additional tool just for sending the announce email. I am not very excited about this option.

**Comment by NotSpecial** [comment]
You raise some good points. But before we can implement this, there are a few things we need to think about:

- How is the sending triggered?
- Can arbitrary text be sent? If not, in which format should we specify what is included in the newsletter?
- Are there any other variables to consider except subject and body?

**Comment by temparus** [comment]
The sending is triggered by the responsible board member (using the announce tool).

The email contains a plaintext version and an HTML version and the sender should be info@amiv.ethz.ch.
As the email content is generated by the announce tool, every content should be sent. Except that HTML and plaintext version are both required.

With the current announce tool, it is possible to send a test-email to an arbitrary email address before sending it to the mailing list. I have no idea if this feature is still being used.

**Comment by NotSpecial** [comment]
I have discussed this with @Leonidaz0r and @hermannsblum and we are all not so sure if we should put an endpoint to send arbitrary mails into the API. The requirements are quite specific and so this would really not be a general functionality for the api, but a part of another tool 'outsourced' into AMIVAPI.

Since we are heading for a container infrastructure anyway, we thought it would really be easy to just have a simple container containing a flask app (or similar) taking care of this. The container could also send out the website for the tool so we keep everything in one place.
(Furthermore the hosting of repositories is done afaik only by github and we wanted to migrate to the ETH gitlab, we would at some point need to host it ourselves anyways)

Is there anything prohibiting us from doing this? I think this would be a "cleaner" solution. I can help with setting up the flask app and container, if you want.

**Comment by temparus** [comment]
I see your point. It wouldn't be a clean solution.

The idea was to integrate the announce tool into the Admintools, which are all client-side themselves, so that we have all administration tools together.
This would mean that we will set up a service just for sending an email.
Another option would be to use a service like [smtpjs](https://smtpjs.com/).

**Comment by temparus** [comment]
A micro-service has been created for sending the announce mail. Closing this issue now.
