### ISSUE TITLE
Include Permissions in session response

### ISSUE THREAD

**Issue by temparus** [amiv-eth/amivapi#266]
We should include the permissions (merged from all groups the user is a member of) with the response to `/sessions`.

This is needed in many tools and therefor should be done in the API.

**Comment by NotSpecial** [comment]
That seems reasonable, I can think of the admin tools as an example, which could show the different control panels (users, groups, etc.) based on permissions.

On the other hand, those cases could also be solved with an "optimistic" approach:

Each resource already informs you which resouce methods are available, e.g. a `GET /` includes links to all resources, including the available methods. This can already tell the tool whether a resource is available or not.

Therefore when a tool aquires a token, it could just start sending requests and act according to the response.

Is there any situation that would not be covered by this approach? Or a situation that would be *significantly* easier to handle by including the permissions in a `GET /sessions`?

**Comment by temparus** [comment]
Isn't the PATCH method always available for example for `/users` as you are allowed to patch your own user?

**Comment by NotSpecial** [comment]
Patching your own user, yes, but only an admin would get permission to `POST /users`.

**Comment by temparus** [comment]
Ah, sure. That's right. `POST` is only available if you have write
permissions. What about `GET` for `/users`? You are allowed to get your own
user data, so it is not possible to determine if you have `read` permission
for the whole resource or only for your own entry.

Am Fr., 4. Mai 2018 um 15:59 Uhr schrieb Alexander Dietmüller <
notifications@github.com>:

**Comment by NotSpecial** [comment]
Sure, but again, is that necessary?

Consider a user management tool in the admin tools as an example:
After a first `GET /` you know which reasources you can read and write (on the resource level),
from this the tool can know that the user tool has to be displayed (I think this makes sense,
even if only a subset of the items is visible to the user)

In the user tool, we already know wheter or not user creation is allowed (from `GET /`), so
according to this a button to create a user could be shown or not.

Finally, for every user that is visible, the tool could show the available actions, e.g.
`PATCH` for your own user, but not for others.

Aside from the first `GET /`, the tool would need to do all other requests anyway.

This way the tool would not require any knowledge about what admin permissions are, i.e.
"what does it mean to be user admin?", since it directly displays only what is allowed for the user.

**Comment by temparus** [comment]
For the Check-in Tool for example, this would allow everyone to log in and create a attendance tracker even if the user has not enough permissions to read all users. 

Currently this is done with a special group.

**Comment by hermannsblum** [comment]
In general, shouldn't `OPTIONS` be used for such queries?

**Comment by temparus** [comment]
Surely, `OPTIONS` is there to check if a given method is available. Since it is possible that a method is available, but can only be used to read one specific entry, this does not imply that the user has enough permissions to do the needed tasks.

**Comment by hermannsblum** [comment]
> For the Check-in Tool for example, this would allow everyone to log in and create a attendance tracker even if the user has not enough permissions to read all users.

> Currently this is done with a special group.

@temparus could you explain this in detail? I think in general as @NotSpecial pointed out we already get all the access information as soon as we need them.

**Comment by NotSpecial** [comment]
Ping @temparus

**Comment by NotSpecial** [comment]
It has been decided to switch AMIVAPI to the VSETH infrastructure. Along with this, we will replace the API auth with the provided infrastructure. This change would wasted time.
