### ISSUE TITLE
Missalignment of Validation and Defaults

### ISSUE THREAD

**Issue by hermannsblum** [amiv-eth/amivapi#272]
I came accross this when editing an event. The field `allow_email_signup` defaults to `false` if not set, and therefore is always send by the API when requesting a document, even if the field is never specified by a user (and especially if `spots` was never specified).
During patching, however, the field must not be filled in if `spots` is not set, which also has no defaults. Therefore, the events document has different valid states for PATCH and for GET, once with and once without `allow_email_signup`.
I'd suggest to either remove the default or the extra validation of `only_if_not_null`

```
'allow_email_signup': {
                'nullable': False,
                'type': 'boolean',
                'default': False,
                'only_if_not_null': 'spots',
                'description': 'If False, only AMIV-Members can sign up for '
                'this event'
}
```

**Comment by temparus** [comment]
I am not sure if I really understand the above configuration:

* `'nullable': False` means that the field can not be null. So that means that the field always has to be set?
* `'only_if_not_null': 'spots` means that this field can only be set if `spots` is not null? Isn't that a contradiction to the `nullable` configuration? Or is this only referred to the value `True`?

**Comment by hermannsblum** [comment]
> So that means that the field always has to be set?

No, it means that the field may either not be set at all, or has to be set to a reasonable value, it cannot be set to `none`. However, in case that the field is not set, it will be set to the `default`, so in this combination it will always be set.

> 'only_if_not_null': 'spots means that this field can only be set if spots is not null? Isn't that a contradiction to the nullable configuration?

This is exactly my point. It does not make sense.

**Comment by temparus** [comment]
I would go with removing the default value. I think it is more reasonable to have the field only set if it is required.

Another remark: The description of this field does not reflect the current behavior. If this field is set to `False`, this only means that the registration is limited to users with a login to the API. This problem is also addressed by #244.

**Comment by NotSpecial** [comment]
I'm currently coming across this issue for the Eve 0.8 update.

The latest consensus is to simply remove the default value, right? I'll implement this then.

**Comment by NotSpecial** [comment]
This issue has been resolved a few commits ago. For simplicity, `allow_email_signup` does not depend on spots anymore, and is not nullable anymore. By default, it is false, and can be set explicitly to true. if the event has no signup, this has of course no effect.
