### ISSUE TITLE
LDAP Connection Errors not handled correctly

### ISSUE THREAD

**Issue by temparus** [amiv-eth/amivapi#312]
LDAP Connection Errors are not handled correctly. See the error report below.

![screenshot from 2018-11-05 20-38-38](https://user-images.githubusercontent.com/12703793/48022458-72320180-e13b-11e8-96b1-094f18d58eed.png)

**Comment by cburchert** [comment]
Do we have a full stacktrace? We catch the exception when we check the password and we should not try to sync the user if the LDAP login fails.

**Comment by cburchert** [comment]
Is it possible that the LDAP went down after checking the password but before syncing the user?

**Comment by cburchert** [comment]
I am not even sure how we are supposed to handle this error. The error code is 500 already. We could catch it and change it to 503 maybe, but that doesn't benefit the user any more than a 500. Any suggestions?

**Comment by temparus** [comment]
You find the detailed error report at https://sentry.amiv.ethz.ch/share/issue/a10a350280ab4fef8f2869388721630f/

**Comment by NotSpecial** [comment]
@cburchert I think we probably should not return a 500, but simply fail the ldap login and only log this internally.

The issue I see is the following: We currently do not catch general connection errors, only LDAP login errors. So if LDAP login fails, we proceed, but if we can't even connect to LDAP, we crash.

This means that if the LDAP server is not reachable, no one can log in anymore, not even users that have set an API password, which should not happen, I think.

Regarding the fix for this: [The ldap3 packet goes a bit overboard with custom exceptions](https://github.com/cannatag/ldap3/blob/master/ldap3/core/exceptions.py), but I think we can use catch the [LDAPCommunicationError](https://github.com/cannatag/ldap3/blob/master/ldap3/core/exceptions.py#L509-L510) and cover all connection issues.

However, this creates a small problem with the error code: If a user wants to login via ldap, but it fails because of the connection, we have to return a proper error code, and I'm not sure how well that fits into the current *check ldap, then check db* flow.

**Comment by cburchert** [comment]
We shouldn't crash for connection errors, if they actually happen at the beginning of the process. The check for successful login catches all LDAP exceptions: https://github.com/NotSpecial/nethz/blob/master/nethz/ldap.py#L149

As nearly all users are logging in via LDAP, it is probably fine if we change this check to just catch the proper authentication failure exception and propagate communication errors outside. Then we can add a check for more ldap exceptions in process_login, which actually aborts with something like 503.

**Comment by NotSpecial** [comment]
You are right!

I should've checked the stack trace more thoroughly (and my own LDAP connector code ;) )
As you point out, we already do what I was proposing above, if LDAP is unreachable, login via DB still works, so all is good on that front.

And yes, since the error did not occur during the login, but the user synchronization, I agree that we should return a 5xx code.

However, I don't think we gain much by changing the code from 500 to 503, as this is only relevant for developers, which can already see the error cause by checking the error logs.
I don't really see how a client would react differently to a 503 compared to a 500, so I think we shouldn't change anything at all.

**Comment by NotSpecial** [comment]
I say we go back to your initial suggestion, leave the 500, and close this issue. Agreed?
