### ISSUE TITLE
Login with email address

### ISSUE THREAD

**Issue by niccantieni** [amiv-eth/amivapi#598]
Truncate any emailadress that matches `*@*ethz.ch` to everything before the `@`.

**Comment by niccantieni** [comment]
Hi @NotSpecial! I discussed it with @temparus, it'a just that today's Erstis are trying to sign in with their emailadress, but that doesn't work, as our logic only uses ETH-LDAP if a ETH-username is used (I think?)

**Comment by NotSpecial** [comment]
Do I get it right that the issue is that ersties try to log in with their email address, not their username?

I guess we could try both at the API level. I'd give this a rather low priority though, as it's pretty easy for people to figure out, I guess ^^

If you need any advice on how to implement it, let me know.

**Comment by temparus** [comment]
With the new ETH login system, users often have to use <nethz>@ethz.ch as their username. In combination with the username label "nethz or email" then mislead them to use the credentials they had to use for other ETH services which includes the @ethz.ch postfix.

It definitely has low priority but would be a nice enhancement to have.
