### ISSUE TITLE
Random ondelete flag

### ISSUE THREAD

**Issue by Leonidaz0r** [amiv-eth/amivapi#75]
Why does GroupUserMember(old: ForwardUser) have an ondelete flag in the group_id(old: forward_id) relationship, but GroupAddressMember(old: ForwardAddress) does not?
If it is necessary ForwardAddress should probably also have it.

**Comment by NotSpecial** [comment]
We actually dont need it. I've read the pages on cascades in sqlalchemy here:
http://docs.sqlalchemy.org/en/latest/orm/cascades.html

The ondelete flag is unique du ForeignKeys and allows to do any action when the key in points to gets deleted (example "SET NULL")

But since we order our parent element to always delete their childs this is unneccesary.

Furthermore our cascade("all", "delete") could be shortened to cascade("all") since the "all" already includes "delete"
