### ISSUE TITLE
Provide password recovery

### ISSUE THREAD

**Issue by NotSpecial** [amiv-eth/amivapi#77]
Since users will be able to set their passwords, there should be some way to reset it (without requiring help of an admin)

**Comment by Leonidaz0r** [comment]
We have two options here as I see it:

1. POST to an endpoint like /passwordrecovery will send a new password to the user via email
Advantage: Very easy to implement
Disadvantage: Could be abused

2. POST to an endpoint like /passwordrecovery will send a one time login:
Advantage: Can not be abused
Disadvantage: Harder to implement

For the second case we could add a new internal field to User objects "one_time_password". Providing that password to /sessions would remove the password and log in the user.
The problem is the same as for confirmations: We need an external tool to do the request or we need to use a GET request for the login.

Opinions?

**Comment by NotSpecial** [comment]
We have some method of changing passwords, and resets can be handled by admins. As most passwords are going over LDAP anyway, there is no real need to spend time on integrating this feature.
