### ISSUE TITLE
POST groupusermembers -> error: user_id

### ISSUE THREAD

**Issue by GiannaP** [amiv-eth/amivapi#90]
only error because gourp_id required. user_id is also required but api doesn't recognize no user_id as error

**Comment by NotSpecial** [comment]
What is happening:

user_id depends on group_id (because depending on the group you might be able to sign up any user or just yourself)

Therefore the API only notifies you about the user_id if the group_id is there.

After evaluating our code it seems that this is quite unnecessary (The validation can be done without waiting for the group_id). I will change the process so you get both messages at the same time.

**Comment by NotSpecial** [comment]
Done in d01675370f950a461866c824346459f316edd6b6
