### ISSUE TITLE
Define event image resolution, validate this somehow?

### ISSUE THREAD

**Issue by NotSpecial** [amiv-eth/amivapi#96]
We have three image fields in events

img_thumbnail
img_web
img_infoscreen

We should specify the resolution and maybe enforce it in the validator

**Comment by fubu** [comment]
Do you mean a minimum resolution, a range or an exact resolution? Or even just aspect ratios (1:1, 4:3, 16:9)? A mix of both?

I'm asking because I think it's a valid use case that I want to upload the raw (high-resolution) material. Which could also have the added benefit of allowing to re-source an image later if the resolution requirements change.

(The image delivery solutions I know of basically all work in the same way: Upload the raw material in any form, and request specific transformations of it. But I see that implementing/running a full-grown image processing pipeline could be too much to ask from AMIV ;))

**Comment by Leonidaz0r** [comment]
Meeting result: We write a validator for aspect ratios, check infoscreen images for 16:9 format and wait for the website people to have some idea of what they need.
